### ISSUE TITLE
Delta Lake —— 老师有对 Delta Lake 做过一些研究么？

### ISSUE THREAD

**Issue by Rianico** [wulei-bj-cn/potatoes#2]
目前 Delta Lake、Hudi、Iceberg 都很火，老师对这部分有了解么？

**Comment by wulei-bj-cn** [comment]
数据湖现在确实很火，不过我这边还没有开始了解，一直在搞机器学习相关，很遗憾~ 后面有机会一起学习吧~

**Comment by Rianico** [comment]
好的，期待这个机会~
